### ISSUE TITLE
1CX M.2 Module + imx8mm: Can't get pcie to initialized

### ISSUE THREAD

**Issue by erikly01** [embeddedartists/uboot-imx#3]
Hi,

I'm using the imx8mm and getting pcie error messags during init. My goal is to get the Embedded Artist 1CX M.2 module up and running.

1. How do I begin to troubleshoot the issue?

2. Do we need an epdev_on regulator for pcie to work?

3. How does the ext_osc = <1> in the device tree relate to the message "pcie phy ppl can't be locked" dmesg

```
[    1.983047] imx6q-pcie 33800000.pcie: 33800000.pcie supply epdev_on not found, using dummy regulator
[    1.992612] OF: PCI: host bridge /pcie@0x33800000 ranges:
[    1.998031] OF: PCI:   No bus range found for /pcie@0x33800000, using [bus 00-ff]
[    2.005529] OF: PCI:    IO 0x1ff80000..0x1ff8ffff -> 0x00000000
[    2.011461] OF: PCI:   MEM 0x18000000..0x1fefffff -> 0x18000000
[    2.017844] imx6q-pcie 33800000.pcie: Initialize PHY with EXT REfCLK!.
[    2.024682] imx6q-pcie 33800000.pcie: PHY Initialization End!.
[    2.051619] imx6q-pcie 33800000.pcie: pcie phy pll can't be locked.
[    2.097900] imx6q-pcie 33800000.pcie: failed to initialize host
[    2.103825] imx6q-pcie 33800000.pcie: unable to add pcie port.
```

**Comment by embeddedartists** [comment]
Please use the contact form on our website if you need support. It is more efficient to use our support system to sort out possible problems you might have using our products. 
https://www.embeddedartists.com/contact-us/
